import { IsNotEmpty, IsString } from 'class-validator';

export class HasAccessDTO {
  // Cognito userId
  @IsString()
  @IsNotEmpty()
  userId: string;

  // Client ID generated by Cognito for AppClients
  @IsString()
  @IsNotEmpty()
  applicationClientId: string;
}
