export const COUNTIES = [
  { id: 1, name: 'Alba', abbreviation: 'AB' },
  { id: 2, name: 'Arad', abbreviation: 'AR' },
  { id: 3, name: 'Arges', abbreviation: 'AG' },
  { id: 5, name: 'Bacau', abbreviation: 'BC' },
  { id: 6, name: 'Bihor', abbreviation: 'BH' },
  { id: 7, name: 'Bistrita-Nasaud', abbreviation: 'BN' },
  { id: 8, name: 'Botosani', abbreviation: 'BT' },
  { id: 9, name: 'Braila', abbreviation: 'BR' },
  { id: 10, name: 'Brasov', abbreviation: 'BV' },
  { id: 11, name: 'Bucuresti', abbreviation: 'B' },
  { id: 18, name: 'Buzau', abbreviation: 'BZ' },
  { id: 19, name: 'Calarasi', abbreviation: 'CL' },
  { id: 20, name: 'Caras Severin', abbreviation: 'CS' },
  { id: 21, name: 'Cluj', abbreviation: 'CJ' },
  { id: 22, name: 'Constanta', abbreviation: 'CT' },
  { id: 23, name: 'Covasna', abbreviation: 'CV' },
  { id: 24, name: 'Dambovita', abbreviation: 'DB' },
  { id: 25, name: 'Dolj', abbreviation: 'DJ' },
  { id: 28, name: 'Galati', abbreviation: 'GL' },
  { id: 29, name: 'Giurgiu', abbreviation: 'GR' },
  { id: 30, name: 'Gorj', abbreviation: 'GJ' },
  { id: 31, name: 'Harghita', abbreviation: 'HR' },
  { id: 33, name: 'Hunedoara', abbreviation: 'HD' },
  { id: 34, name: 'Ialomita', abbreviation: 'IL' },
  { id: 35, name: 'Iasi', abbreviation: 'IS' },
  { id: 36, name: 'Ilfov', abbreviation: 'IF' },
  { id: 39, name: 'Maramures', abbreviation: 'MM' },
  { id: 40, name: 'Mehedinti', abbreviation: 'MH' },
  { id: 41, name: 'Mures', abbreviation: 'MS' },
  { id: 42, name: 'Neamt', abbreviation: 'NT' },
  { id: 43, name: 'Olt', abbreviation: 'OT' },
  { id: 44, name: 'Prahova', abbreviation: 'PH' },
  { id: 45, name: 'Salaj', abbreviation: 'SJ' },
  { id: 46, name: 'Satu Mare', abbreviation: 'SM' },
  { id: 47, name: 'Sibiu', abbreviation: 'SB' },
  { id: 48, name: 'Suceava', abbreviation: 'SV' },
  { id: 49, name: 'Teleorman', abbreviation: 'TR' },
  { id: 50, name: 'Timis', abbreviation: 'TM' },
  { id: 51, name: 'Tulcea', abbreviation: 'TL' },
  { id: 52, name: 'Valcea', abbreviation: 'VL' },
  { id: 53, name: 'Vaslui', abbreviation: 'VS' },
  { id: 54, name: 'Vrancea', abbreviation: 'VN' },
];
