export const COUNTIES = [
  { id: 1, name: 'Alba', abbreviation: 'AB', regionId: 9 },
  { id: 2, name: 'Arad', abbreviation: 'AR', regionId: 3 },
  { id: 3, name: 'Arges', abbreviation: 'AG', regionId: 7 },
  { id: 5, name: 'Bacau', abbreviation: 'BC', regionId: 6 },
  { id: 6, name: 'Bihor', abbreviation: 'BH', regionId: 3 },
  { id: 7, name: 'Bistrita-Nasaud', abbreviation: 'BN', regionId: 9 },
  { id: 8, name: 'Botosani', abbreviation: 'BT', regionId: 2 },
  { id: 9, name: 'Braila', abbreviation: 'BR', regionId: 7 },
  { id: 10, name: 'Brasov', abbreviation: 'BV', regionId: 9 },
  { id: 11, name: 'Bucuresti', abbreviation: 'B', regionId: 7 },
  { id: 18, name: 'Buzau', abbreviation: 'BZ', regionId: 7 },
  { id: 19, name: 'Calarasi', abbreviation: 'CL', regionId: 7 },
  { id: 20, name: 'Caras Severin', abbreviation: 'CS', regionId: 1 },
  { id: 21, name: 'Cluj', abbreviation: 'CJ', regionId: 9 },
  { id: 22, name: 'Constanta', abbreviation: 'CT', regionId: 4 },
  { id: 23, name: 'Covasna', abbreviation: 'CV', regionId: 9 },
  { id: 24, name: 'Dambovita', abbreviation: 'DB', regionId: 7 },
  { id: 25, name: 'Dolj', abbreviation: 'DJ', regionId: 8 },
  { id: 28, name: 'Galati', abbreviation: 'GL', regionId: 6 },
  { id: 29, name: 'Giurgiu', abbreviation: 'GR', regionId: 7 },
  { id: 30, name: 'Gorj', abbreviation: 'GJ', regionId: 8 },
  { id: 31, name: 'Harghita', abbreviation: 'HR', regionId: 9 },
  { id: 33, name: 'Hunedoara', abbreviation: 'HD', regionId: 9 },
  { id: 34, name: 'Ialomita', abbreviation: 'IL', regionId: 7 },
  { id: 35, name: 'Iasi', abbreviation: 'IS', regionId: 6 },
  { id: 36, name: 'Ilfov', abbreviation: 'IF', regionId: 7 },
  { id: 39, name: 'Maramures', abbreviation: 'MM', regionId: 5 },
  { id: 40, name: 'Mehedinti', abbreviation: 'MH', regionId: 8 },
  { id: 41, name: 'Mures', abbreviation: 'MS', regionId: 9 },
  { id: 42, name: 'Neamt', abbreviation: 'NT', regionId: 6 },
  { id: 43, name: 'Olt', abbreviation: 'OT', regionId: 8 },
  { id: 44, name: 'Prahova', abbreviation: 'PH', regionId: 7 },
  { id: 45, name: 'Salaj', abbreviation: 'SJ', regionId: 9 },
  { id: 46, name: 'Satu Mare', abbreviation: 'SM', regionId: 5 },
  { id: 47, name: 'Sibiu', abbreviation: 'SB', regionId: 9 },
  { id: 48, name: 'Suceava', abbreviation: 'SV', regionId: 2 },
  { id: 49, name: 'Teleorman', abbreviation: 'TR', regionId: 7 },
  { id: 50, name: 'Timis', abbreviation: 'TM', regionId: 1 },
  { id: 51, name: 'Tulcea', abbreviation: 'TL', regionId: 4 },
  { id: 52, name: 'Valcea', abbreviation: 'VL', regionId: 8 },
  { id: 53, name: 'Vaslui', abbreviation: 'VS', regionId: 6 },
  { id: 54, name: 'Vrancea', abbreviation: 'VN', regionId: 8 },
];
