export const COUNTIES = [
  { id: 1, name: 'Alba', abbreviation: 'AB', status: 1 },
  { id: 2, name: 'Arad', abbreviation: 'AR', status: 1 },
  { id: 3, name: 'Arges', abbreviation: 'AG', status: 1 },
  { id: 4, name: 'AUSTRIA', abbreviation: '', status: 1 },
  { id: 5, name: 'Bacau', abbreviation: 'BC', status: 1 },
  { id: 6, name: 'Bihor', abbreviation: 'BH', status: 1 },
  { id: 7, name: 'Bistrita-Nasaud', abbreviation: 'BN', status: 1 },
  { id: 8, name: 'Botosani', abbreviation: 'BT', status: 1 },
  { id: 9, name: 'Braila', abbreviation: 'BR', status: 1 },
  { id: 10, name: 'Brasov', abbreviation: 'BV', status: 1 },
  { id: 11, name: 'Bucuresti', abbreviation: 'B', status: 1 },
  { id: 18, name: 'Buzau', abbreviation: 'BZ', status: 1 },
  { id: 19, name: 'Calarasi', abbreviation: 'CL', status: 1 },
  { id: 20, name: 'Caras Severin', abbreviation: 'CS', status: 1 },
  { id: 21, name: 'Cluj', abbreviation: 'CJ', status: 1 },
  { id: 22, name: 'Constanta', abbreviation: 'CT', status: 1 },
  { id: 23, name: 'Covasna', abbreviation: 'CV', status: 1 },
  { id: 24, name: 'Dambovita', abbreviation: 'DB', status: 1 },
  { id: 25, name: 'Dolj', abbreviation: 'DJ', status: 1 },
  { id: 26, name: 'Dublin 2', abbreviation: '', status: 1 },
  { id: 27, name: 'ESSEX', abbreviation: '', status: 1 },
  { id: 28, name: 'Galati', abbreviation: 'GL', status: 1 },
  { id: 29, name: 'Giurgiu', abbreviation: 'GR', status: 1 },
  { id: 30, name: 'Gorj', abbreviation: 'GJ', status: 1 },
  { id: 31, name: 'Harghita', abbreviation: 'HR', status: 1 },
  { id: 32, name: 'Hl. Blut', abbreviation: '', status: 1 },
  { id: 33, name: 'Hunedoara', abbreviation: 'HD', status: 1 },
  { id: 34, name: 'Ialomita', abbreviation: 'IL', status: 1 },
  { id: 35, name: 'Iasi', abbreviation: 'IS', status: 1 },
  { id: 36, name: 'Ilfov', abbreviation: 'IF', status: 1 },
  { id: 37, name: 'ILLINOIS', abbreviation: '', status: 1 },
  { id: 38, name: 'Judet', abbreviation: '', status: 1 },
  { id: 39, name: 'Maramures', abbreviation: 'MM', status: 1 },
  { id: 40, name: 'Mehedinti', abbreviation: 'MH', status: 1 },
  { id: 41, name: 'Mures', abbreviation: 'MS', status: 1 },
  { id: 42, name: 'Neamt', abbreviation: 'NT', status: 1 },
  { id: 43, name: 'Olt', abbreviation: 'OT', status: 1 },
  { id: 44, name: 'Prahova', abbreviation: 'PH', status: 1 },
  { id: 45, name: 'Salaj', abbreviation: 'SJ', status: 1 },
  { id: 46, name: 'Satu Mare', abbreviation: 'SM', status: 1 },
  { id: 47, name: 'Sibiu', abbreviation: 'SB', status: 1 },
  { id: 48, name: 'Suceava', abbreviation: 'SV', status: 1 },
  { id: 49, name: 'Teleorman', abbreviation: 'TR', status: 1 },
  { id: 50, name: 'Timis', abbreviation: 'TM', status: 1 },
  { id: 51, name: 'Tulcea', abbreviation: 'TL', status: 1 },
  { id: 52, name: 'Valcea', abbreviation: 'VL', status: 1 },
  { id: 53, name: 'Vaslui', abbreviation: 'VS', status: 1 },
  { id: 54, name: 'Vrancea', abbreviation: 'VN', status: 1 },
];
