export const DOMAINS = [
  { id: 1, name: 'Advocacy' },
  { id: 2, name: 'Artă & Cultură' },
  { id: 3, name: 'Tehnologie Civică' },
  { id: 4, name: 'Societatea Civilă - Participare Civică' },
  { id: 5, name: 'Societatea Civilă - Comunitate' },
  { id: 6, name: 'Societatea Civilă - Voluntariat' },
  { id: 7, name: 'Dezvoltarea sectorului ONG' },
  { id: 8, name: 'Democrație' },
  { id: 9, name: 'Democrație - Media' },
  { id: 10, name: 'Democrație - Transparență' },
  { id: 11, name: 'Intervenții În Caz De Dezastru' },
  { id: 12, name: 'Creștere Economică - Dezvoltare rurală' },
  { id: 13, name: 'Creștere Economică - Antreprenoriat social' },
  { id: 14, name: 'Creștere Economică - Dezvoltare urbană' },
  { id: 15, name: 'Educație' },
  { id: 16, name: 'Educație Digitală' },
  { id: 17, name: 'Educație - Învățare Continuă' },
  { id: 18, name: 'Educație Pentru Copiii cu CES' },
  { id: 19, name: 'Educație Incluzivă' },
  { id: 20, name: 'Mediu' },
  { id: 21, name: 'Mediu - Animale și Faună sălbatică' },
  { id: 22, name: 'Mediu - Combaterea Schimbărilor Climatice' },
  { id: 23, name: 'Mediu - Agricultură Sustenabilă' },
  { id: 24, name: 'Sănătate' },
  { id: 25, name: 'Sănătate - Intervenție de Urgență' },
  { id: 26, name: 'Sănătate - HIV/AIDS' },
  { id: 27, name: 'Sănătate Mentală' },
  { id: 28, name: 'Sănătate Fizică' },
  { id: 29, name: 'Sănătate Reproductivă' },
  { id: 30, name: 'Drepturile Omului' },
  { id: 31, name: 'Drepturile Omului - Anti-Discriminare' },
  { id: 32, name: 'Drepturile Omului - Copii' },
  { id: 33, name: 'Drepturile Omului - Dizabilități' },
  { id: 34, name: 'Drepturile Omului - Violență Domestică' },
  { id: 35, name: 'Drepturile Omului - Egalitate de Gen' },
  { id: 36, name: 'Drepturile Omului - LGBTQ+' },
  { id: 37, name: 'Drepturile Omului - Minorități' },
  { id: 38, name: 'Drepturile Omului - Refugiați' },
  { id: 39, name: 'Drepturile Omului - Femei' },
  { id: 40, name: 'Ajutor Umanitar' },
  { id: 41, name: 'Cooperare Internațională' },
  { id: 42, name: 'Asistență Juridică' },
  { id: 43, name: 'Migrație' },
  { id: 44, name: 'Altceva/General' },
  { id: 45, name: 'Filantropie' },
  { id: 46, name: 'Combaterea Sărăciei - Apă Curată' },
  { id: 47, name: 'Combaterea Sărăciei - Securitate Alimentară' },
  { id: 48, name: 'Combaterea Sărăciei - Locuințe Sigure' },
  { id: 49, name: 'Cercetare' },
  { id: 50, name: 'Servicii Sociale' },
  { id: 51, name: 'Sport' },
];
