export const ORGANIZATION_ERRORS = {
  RESTRICT: 'ORG_020',
};

export const USER_ERRORS = {
  RESTRICT: 'USR_012',
  NOT_FOUND: 'USR_007',
  ALREADY_EXISTS_EMAIL: 'USR_008',
  ALREADY_EXISTS_PHONE: 'USR_013',
};
