export const HTTP_ERRORS_MESSAGES = {
  ORGANIZATION: 'Organization not found',
  PARTNER: 'Partner not found',
  INVESTOR: 'Investor not found',
  REGION: 'Missing region(s)',
  LOCAL: 'Missing city/cities',
  MISSING_FEDERATIONS: 'Missing federations',
  MISSING_COALITIONS: 'Missing coalitions',
  MISSING_BRANCHES: 'Missing branches',
  MISSING_INTERNATIONAL_ORGANIZATION: 'Missing International Organization',
  MINIMUM_DIRECTORS: 'Minimum 3 directors',
  ANAF_ERROR: 'Incoming data not corresponding with data from ANAF',
  UPLOAD_FILES: 'Error while uploading the files',
  REPORT_NOT_FOUND: 'Report not found',
};

export const ERROR_CODES = {
  ORG001: 'ORG001',
  ORG002: 'ORG002',
  ORG003: 'ORG003',
  ORG004: 'ORG004',
  ORG005: 'ORG005',
  ORG006: 'ORG006',
  ORG007: 'ORG007',
  ORG008: 'ORG008',
  ORG009: 'ORG009',
  ORG010: 'ORG010',
  ORG011: 'ORG011',
  ORG012: 'ORG012',
  ORG013: 'ORG013',
  ANAF001: 'ANAF001',
};
